# Generated by Django 6.0.4 on 2026-04-27 09:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id_instansi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_instansi', models.CharField(max_length=100)),
                ('no_telp', models.CharField(max_length=15)),
                ('jenis_instansi', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('instansi', 'instansi')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('instansi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instansi', to='aduan.instansi')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=100)),
                ('deksripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('ODGJ', 'ODGJ'), ('PGOT', 'PGOT')])),
                ('latitude', models.FloatField(max_length=15)),
                ('longitude', models.FloatField(max_length=15)),
                ('status', models.CharField(choices=[('selesai', 'selesai'), ('proses', 'proses'), ('menunggu', 'menunggu')], default='menunggu')),
                ('tgl_laporan', models.DateField()),
                ('instansi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instansi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
