# Generated by Django 5.2.13 on 2026-04-09 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('no_hp', models.IntegerField()),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
