# Generated by Django 6.0.4 on 2026-04-27 11:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id_instansi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_instansi', models.CharField(max_length=100)),
                ('no_telp', models.CharField(max_length=15, unique=True)),
                ('jenis_instansi', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('no_hp', models.CharField(max_length=15, unique=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('instansi', 'instansi')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=100)),
                ('tgl_laporan', models.DateTimeField()),
                ('deskripsi', models.TextField()),
                ('kategori', models.CharField(choices=[('ODGJ', 'ODGJ'), ('PGOT', 'PGOT')], max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('selesai', 'selesai'), ('proses', 'proses'), ('menunggu', 'menunggu')], max_length=10)),
                ('instansi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aduan.instansi')),
            ],
        ),
    ]
