# Generated by Django 5.2.13 on 2026-04-09 05:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id_instansi', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_instansi', models.CharField(max_length=100)),
                ('no_telp', models.IntegerField()),
                ('jenis_instansi', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='aduan.user')),
            ],
        ),
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id_laporan', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.CharField(max_length=255)),
                ('deksripsi', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=255)),
                ('latitude', models.FloatField(max_length=50)),
                ('longitude', models.FloatField(max_length=50)),
                ('status', models.CharField(choices=[('selesai', 'selesai'), ('proses', 'proses'), ('menunggu', 'menunggu')], default='menunggu')),
                ('tgl_laporan', models.DateField()),
                ('instansi_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instansi', to='aduan.user')),
            ],
        ),
    ]
