# Generated by Django 6.0.4 on 2026-04-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='nama_pelapor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
