# Generated by Django 5.2.13 on 2026-04-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0002_instansi_laporan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='no_telp',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='deksripsi',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='foto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='kategori',
            field=models.CharField(choices=[('ODGJ', 'ODGJ'), ('PGOT', 'PGOT')]),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='latitude',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='longitude',
            field=models.FloatField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='nama',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_hp',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('instansi', 'instansi')]),
        ),
    ]
