# Generated by Django 6.0.4 on 2026-04-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0002_laporan_nama_pelapor'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='email_pelapor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='hubungan_pelapor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='no_hp_pelapor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='nama_pelapor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
