# Generated by Django 6.0.4 on 2026-04-21 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0003_alter_instansi_no_telp_alter_laporan_deksripsi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('instansi', 'instansi')], max_length=20),
        ),
    ]
