# Generated by Django 5.2.13 on 2026-04-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0003_alter_instansi_no_telp_alter_laporan_deksripsi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laporan',
            name='email_pelapor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='hubungan_pelapor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laporan',
            name='nama_pelapor',
            field=models.CharField(default='Anonim', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laporan',
            name='no_hp_pelapor',
            field=models.CharField(default='081234567812', max_length=15),
            preserve_default=False,
        ),
    ]
