# Generated by Django 5.2.13 on 2026-04-21 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0004_laporan_email_pelapor_laporan_hubungan_pelapor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporan',
            name='instansi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instansi', to='aduan.instansi'),
        ),
    ]
