# Generated by Django 5.2.13 on 2026-04-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0005_remove_instansi_user_id_instansi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instansi',
            name='user',
        ),
    ]
