# Generated by Django 5.2.13 on 2026-04-27 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0005_alter_laporan_instansi_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laporan',
            old_name='deksripsi',
            new_name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='instansi',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='email_pelapor',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='hubungan_pelapor',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='nama_pelapor',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='no_hp_pelapor',
        ),
        migrations.AlterField(
            model_name='instansi',
            name='no_telp',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='instansi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aduan.instansi'),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='kategori',
            field=models.CharField(choices=[('ODGJ', 'ODGJ'), ('PGOT', 'PGOT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.CharField(choices=[('selesai', 'selesai'), ('proses', 'proses'), ('menunggu', 'menunggu')], max_length=10),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='tgl_laporan',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_hp',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('instansi', 'instansi')], max_length=20),
        ),
    ]
