# Generated by Django 5.2.13 on 2026-04-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0006_remove_instansi_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instansi_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instansi', to='aduan.instansi'),
        ),
    ]
