# Generated by Django 5.2.13 on 2026-04-20 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aduan', '0007_user_instansi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='instansi_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instansi', to='aduan.instansi'),
        ),
    ]
